### PR TITLE
Added Czech translation

### PR DESCRIPTION
**Pull request by svasek**

### CODE REVIEW

**Review by BenPru — CHANGES_REQUESTED** [review]
Special Chats are not allowed

Please replace them with unicodes.
E.g. see German translation file äöü...
E.g.         "name": "TČ"

**Comment by svasek** [comment]
Hi @BenPru 
I've converted the special characters in the file to UTF16. 
However, on my Home Assistant it works even without that.

**Comment by svasek** [comment]
Hi @BenPru, 
Is there anything I could improve to make the pull request accepted?

**Review by augi — APPROVED** [review]
Please note I'm native Czech, and this translation looks good 👍

**Comment by svasek** [comment]
Hi @BenPru ,
I can confirm the translation file is compatible with the [2024.9.23-Beta](https://github.com/BenPru/luxtronik/releases/tag/2024.9.23-Beta) release 👍.
I use it on my HASS instance.

**Review by BenPru — APPROVED** [review]

**Pull request merged**
